core/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.urls import re_path as url
# from crudbuilder import urls

# from core import views
from .views import (CafeFormsetView, VisitView, TestView, add_dish_library, TableView, dishinfo,
                    add_dish_lib, CafesListView, Cafe_cab, VisitsView, VisitCab,
                    DishesListView, add_new_dish, add_new_dish_collection, TypeDictListView,
                    DictView, TypeEditTableView, TypeDictUpdateListView, ClassDictListView, ClassDictUpdateListView,
                    ClassEditTableView, BestDishesListView, MyVisitsListView,
                    VisitsList, DishPhotosList, StartView, Privacy, StorytalesView
                    )
# from iommi import Form
# from core.models import DishModel
# from iommi.views import crud_views
# from core.models import CulinaryClassModel

app_name = 'core'
urlpatterns = [

    # path('',
    #      RedirectView.as_view(url='/dishes/', permanent=True), name='pages-root'),

    path('', StartView.as_view(), name='start'),
    path('cafes/', CafesListView.as_view(), name='cafes'),

    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^crud/', include(urls)),

    path('dictionaries/', DictView.as_view(), name='dicts'),
    path('dictionaries/types/', TypeDictListView.as_view(), name='types'),
    path('dictionaries/types/<int:tpk>/', TypeDictUpdateListView.as_view(), name='updatetypes'),
    path('edittype/<int:pk>/', TypeEditTableView.as_view(), name='edittype'),

    path('dictionaries/classes/', ClassDictListView.as_view(), name='classes'),
    path('dictionaries/classes/<int:cpk>/', ClassDictUpdateListView.as_view(), name='updateclasses'),
    path('editclass/<int:pk>/', ClassEditTableView.as_view(), name='editclass'),
    # path('iommi/', crud_views(model=CulinaryClassModel)),
    # path('iommi/', iommitest, name='iommi'),

    path('cafe/<int:pk>/', Cafe_cab.as_view(extra_context={'edit': True}), name='cafe_cab'),
    # path('cafe/<int:pk>/?way=list', Cafe_cab.as_view(), name='cafe_cab_list'),

    path('cafe/add_cafe/', Cafe_cab.as_view(extra_context={'add': True}), name='cafe_add'),

    # path('visits/', VisitsView.as_view(), name='visit'),
    path('visits/<int:pk>/', VisitsView.as_view(), name='visits'),

    path('cafe/<int:cpk>/<int:pk>/', VisitCab.as_view(), name='visit'),

    # path('visits/', VisitsView.as_view(), name='allvisits'),

    path('visitcab/<int:cpk>/', VisitCab.as_view(extra_context={'add': True}), name='visitcab'),

    path('disheslist/<int:vpk>/', DishesListView.as_view(), name='dishlist'),

    path('adddish/<int:vpk>/', add_new_dish_collection.as_view(), name='add_new_dish'),

    # path('cafe/<int:cpk>/<int:vpk>/<int:pk>/', add_new_dish.as_view(), name='dishes'),

    path('cafe/<int:cpk>/<int:vpk>/<int:pk>/', add_new_dish_collection.as_view(extra_context={'edit': True}), name='dishes'),

    path('dishinfo/', dishinfo, name='dishinfo'),

    path('dishes/', BestDishesListView.as_view(), name='bestdishes'),

    path('myvisits/', MyVisitsListView.as_view(), name='myvisits'),

    path('visitlist/<int:pk>/', VisitsList.as_view(), name='visitlist'),

    path('dishesphotos/<int:pk>/', DishPhotosList.as_view(), name='visitlist'),

    path('privacy/', Privacy.as_view(), name='visitlist'),

    path('storytales/<int:pk>/', StorytalesView.as_view(), name='storytales'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

foodster/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path as url
# from core.views import DishAutocomplete, TypeOfKitchenAutocomplete
# from core.views import display_cafes, delete_cafe, add_cafe
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog
# from crudbuilder import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    # path(r'^', include('djangocms_forms.urls')),
    # path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('', include('core.urls')),
    # path('rating/', include('rating.urls')),
    # url(r'^photologue/', include('photologue.urls',namespace='photologue')),
    # path('gallery/', include('gallery.urls')),
    path('system/', include('system.urls')),
    # url(r'^dish-autocomplete/$', DishAutocomplete.as_view(create_field='title'), name='dish-autocomplete'),
    # url(r'^typeofkitchen-autocomplete/$', TypeOfKitchenAutocomplete.as_view(create_field='title'), name='typeofkitchen-autocomplete'),
    path(
        'jsi18n/',
        cache_page(3600)(JavaScriptCatalog.as_view(packages=['formset'])),
        name='javascript-catalog'
    ),
    # url(r'^crud/', include(urls)),

]


if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
# if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns


urlpatterns.append(path('', include('cms.urls')))

# the new django admin sidebar is bad UX in django CMS custom admin views.
# admin.site.enable_nav_sidebar = False


urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path as url
# from core.views import DishAutocomplete, TypeOfKitchenAutocomplete
# from core.views import display_cafes, delete_cafe, add_cafe
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog
# from crudbuilder import urls


urlpatterns = [
    path('admin/', admin.site.urls),

    # path(r'^', include('djangocms_forms.urls')),
    # path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    # path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('', include('core.urls')),
    # path('rating/', include('rating.urls')),
    # url(r'^photologue/', include('photologue.urls',namespace='photologue')),
    # path('gallery/', include('gallery.urls')),
    path('system/', include('system.urls')),
    # url(r'^dish-autocomplete/$', DishAutocomplete.as_view(create_field='title'), name='dish-autocomplete'),
    # url(r'^typeofkitchen-autocomplete/$', TypeOfKitchenAutocomplete.as_view(create_field='title'), name='typeofkitchen-autocomplete'),

    path(
        'jsi18n/',
        cache_page(3600)(JavaScriptCatalog.as_view(packages=['formset'])),
        name='javascript-catalog'
    ),
    # url(r'^crud/', include(urls)),

]


if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
# if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns


urlpatterns.append(path('', include('cms.urls')))


# the new django admin sidebar is bad UX in django CMS custom admin views.
# admin.site.enable_nav_sidebar = False

core/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.functional import empty
from django_resized import ResizedImageField
from django.contrib.contenttypes.fields import GenericRelation
from location_field.models.plain import PlainLocationField
from taggit.managers import TaggableManager
from django.db import models
from cms.models.pluginmodel import CMSPlugin
from taggit.models import Tag
from django.utils.translation import gettext_lazy as _


# from rating.models import Rating

# Create your models here.
class TypeOfDishes(models.Model):
    title = models.CharField(max_length=200,)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Type_of_dishes"


class DishCatalog(models.Model):
    name = models.CharField(max_length=200,)
    # type_fk = models.ForeignKey(TypeOfDishes, on_delete=models.CASCADE, null=True, related_name='type_dishes',)

    tags = TaggableManager(
        blank=True,
        verbose_name=_('Tags')
    )

    class Meta:
        verbose_name_plural = "DishesCatalog"

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'<{self.__class__.__name__}: "{self.name}">'


""" нужно добавить для кафе еще webaddress, телефон. Кроме того нужен Город """

class CafeModel(models.Model):

    title = models.CharField(verbose_name="Название", max_length=200)
    content = models.TextField(verbose_name="Описание")
    typeofkitchen = models.TextField(verbose_name="Специфика заведения")

    city = models.CharField(verbose_name="Город", null=True, blank=True, max_length=200)
    address = models.TextField(verbose_name="Адрес", null=True, blank=True)
    wwwaddress = models.URLField(verbose_name="Web адрес", null=True, blank=True)

    # location = PlainLocationField(based_fields=['address'], zoom=7, null=True)
    average_rating = models.DecimalField(max_digits=5, decimal_places=2, default=0, verbose_name="Рейтинг")

    date_created = models.DateTimeField(default=timezone.now)

    tags = TaggableManager(
        blank=True,
        verbose_name=_('Tags')
    )

    class Meta:
        verbose_name_plural = "Cafes"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/cafe/{self.pk}/'

    def get_stories(self):
        """Находит статьи, где в плагине TagSelector выбрано это кафе"""
        from taggit.models import TaggedItem
        from cms.models import Placeholder
        from djangocms_stories.models import PostContent  # ← Вот нужная модель!

        # 1. Находим теги этого кафе
        cafe_tagged_items = TaggedItem.objects.filter(
            content_type__model='cafemodel',
            object_id=self.pk
        ).select_related('tag')

        cafe_tag_ids = cafe_tagged_items.values_list('tag_id', flat=True)

        if not cafe_tag_ids:
            return PostContent.objects.none()

        # 2. Находим плагины TagSelector с этими тегами
        tag_selectors = TagSelector.objects.filter(
            tags__id__in=cafe_tag_ids
        ).select_related('cmsplugin_ptr')

        plugin_ids = tag_selectors.values_list('cmsplugin_ptr_id', flat=True)

        if not plugin_ids:
            return PostContent.objects.none()

        # 3. Находим placeholder'ы с этими плагинами
        placeholders = Placeholder.objects.filter(
            cmsplugin__id__in=plugin_ids
        ).distinct()

        # 4. Получаем ID статей из object_id placeholder'ов
        story_ids = placeholders.values_list('object_id', flat=True)

        # 5. Возвращаем статьи
        return PostContent.objects.filter(pk__in=story_ids).distinct()

class CafeImageModel(models.Model):

    title = models.CharField(max_length=200, default='')
    # image = models.ImageField(upload_to='media')
    image = ResizedImageField(upload_to='media/cafes/%Y.%m.%d')
    cafe_fk = models.ForeignKey(CafeModel, on_delete=models.CASCADE, related_name='cafe_images',)

    def __str__(self):
        return self.title


class VisitModel(models.Model):

    data = models.DateTimeField(verbose_name="Дата визита")
    cafe_fk = models.ForeignKey(CafeModel, on_delete=models.CASCADE)
    description = models.TextField(verbose_name="Описание визита")
    average_dish_rating = models.DecimalField(max_digits=5, decimal_places=2, default=0, verbose_name="Рейтинг блюд визита")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    register = models.BooleanField(default=True)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name_plural = "Visits"

    def get_absolute_url(self):
        if self.cafe_fk:
            return self.cafe_fk.get_absolute_url()+str(self.pk)+"/"
        return '#none'


class VisitImageModel(models.Model):

    title = models.CharField(max_length=200, default='')
    # image = models.ImageField(upload_to='media')
    image = ResizedImageField(upload_to='media/visits/%Y.%m.%d')
    visit_fk = models.ForeignKey(VisitModel, on_delete=models.CASCADE, related_name='visit_images',)

    def __str__(self):
        return self.title


class CulinaryClassModel(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return 'none'



class TypeOfKitchen(models.Model):
    name = models.CharField(max_length=200)

    tags = TaggableManager(
        blank=True,
        verbose_name=_('Tags')
    )

    def __str__(self):
        return self.name


class DishLibraryModel(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наименование')
    dishcatalog_fk = models.ForeignKey(DishCatalog, on_delete=models.CASCADE, verbose_name='Блюдо-образец для сравнения', null=True, blank=True)
    type_of_kitchen_fk = models.ForeignKey(TypeOfKitchen, on_delete=models.CASCADE, verbose_name='Тип кухни')
    cafe_fk = models.ForeignKey(CafeModel, on_delete=models.CASCADE, verbose_name='', null=True, blank=True)
    # CulinaryClassModel_fk = models.ForeignKey(CulinaryClassModel, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Кулинарные классы')
    CulinaryClassModel_fk = models.ManyToManyField(CulinaryClassModel, verbose_name='Кулинарные классы')

    tags = TaggableManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "LibraryDishes"

    def get_absolute_url(self):
        return f'/dishes/{self.pk}/'


class DishModel(models.Model):

    dish_fk = models.ForeignKey(DishLibraryModel,on_delete=models.CASCADE, related_name='bestdishes',)
    visit_fk = models.ForeignKey(VisitModel, on_delete=models.CASCADE, related_name='visit_dishes')
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    tags = TaggableManager()

    price = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    TYPE_SELECT = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        # ('6', '6'),
        # ('7', '7'),
    )
    rating=models.CharField(max_length=11,choices=TYPE_SELECT,default='0')
    rating2 = models.CharField(max_length=11, choices=TYPE_SELECT, default='0')

    def __str__(self):

        return self.dish_fk.name

    class Meta:
        verbose_name_plural = "Dishes"

    def get_absolute_url(self):
        return self.visit_fk.get_absolute_url()+str(self.pk)+"/"



class DishImageModel(models.Model):

    title = models.CharField(max_length=200, default='')
    # image = models.ImageField(upload_to='media')
    image = ResizedImageField(upload_to='media/dishes/%Y.%m.%d')
    dish_fk = models.ForeignKey(DishModel, on_delete=models.CASCADE, related_name='dish_images',)

    def __str__(self):
        return self.title


class SiteSettings(models.Model):
    show_register_button = models.BooleanField(
        default=True,
        verbose_name="Показывать кнопку регистрации"
    )

    class Meta:
        verbose_name = "Настройки сайта"
        verbose_name_plural = "Настройки сайта"

    def save(self, *args, **kwargs):
        # Оставляем только одну запись настроек
        self.pk = 1
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

class IntroImageModel(models.Model):

    title = models.CharField(max_length=200, default='')
    image = ResizedImageField(upload_to='media/intro')

    def __str__(self):
        return self.title


class TagSelector(CMSPlugin):
    """Модель плагина для хранения выбранных тегов"""
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        related_name='tag_selector_plugins',
        verbose_name=_('Selected Tags')
    )

    def __str__(self):
        # Проверяем, есть ли у объекта ID (сохранен ли он в БД)
        if self.pk:
            count = self.tags.count()
            return f'Tag Selector ({count} tags)'
        return 'New Tag Selector'


core/templates/add_visit.html
{% load i18n %}
{% load formsetify %}
<div class="modal-content modal-dialog modal-xl" hx-target="this">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Новое посещение</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

            <django-formset endpoint="{{ request.path }}" csrf-token="{{ csrf_token }}">
              {% render_form form "bootstrap" field_classes="mb-2" %}
              {% if add %}
                <button type="button" df-click="submit({add: true}) -> proceed">{% trans "Добавить посещение" %}</button>
              {% else %}
                <button type="button" df-click="submit({update: true}) -> proceed">{% trans "Update" %}</button>
                <button type="button" df-click="submit({delete: true}) -> proceed">{% trans "Delete" %}</button>
              {% endif %}
            </django-formset>

{#            <form method="post" >#}
{#                {% csrf_token %}#}
{#                <p>#}
{#                    {{ form.as_p }}#}
{#                </p>#}
{##}
{#                <input type="submit"#}
{#                       hx-post="{% url 'core:add_visit' cafe.id %}"#}
{#                       hx-trigger="click"#}
{#                       hx-target="#search-results"#}
{#                       hx-indicator=".htmx-indicator"#}
{#                data-bs-dismiss="modal">#}
{#            </form>#}
{##}
      </div>
      <div class="modal-footer">
      </div>
</div>

core/templates/cafe_cab.html
{% extends "minimal.html" %}
{% load formsetify %}
{% load render_table from django_tables2 %}
{% load thumbnail %}


{%  block content %}

    <div id="cab">
        <div class="bg-secondary">
        <div class="container py-3">
            <div id="cardSlider" class="f-carousel mb-8 py-3 pb-0">
                <div class="f-carousel__viewport">
                    {% for image in images %}
                        {% thumbnail image.image 400x400 crop="smart" upscale=True as im %}
                            <figure class="f-carousel__slide">
                                <img
                                    width=500
                                    height=500
                                    data-fancybox="gallery"
                                    data-src="/media/{{ image.image }}"
                                    data-lazy-src="{{ im.url }}"
                                    class="mb-4 img-fluid rounded"
                                    alt="Square image"
                                    loading="lazy"
                                >
                            </figure>
                    {% endfor %}
                </div>
            </div>
        </div>
        </div>
{#        <div id="cabtitle" class="container">#}
{#            <H5>#}
{#                Кабинет кафе: {{ object }}#}
{#            </H5>#}
{#        </div>#}
        <nav>
            <div class="nav nav-tabs nav-justified custom_tab_style1" id="myTab" role="tablist">
                <a class="nav-link backnav-link"
                   href="/cafes/"
                   id="back-tab"
                   role="tab"
                   style="width: auto; min-width: 88px; padding: 1rem; text-decoration: none; display: inline-flex; align-items: center; justify-content: center;">
                    Назад
                </a>
                {% if way == 'list' %}
                <button class="nav-link" style="width: auto; min-width: 88px; padding: 0.25rem;" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Карточка кафе</button>
                <button class="nav-link active" style="width: auto; min-width: 88px; padding: 0.25rem;" id="visits-tab" data-bs-toggle="tab" data-bs-target="#visitstable" type="button" role="tab" aria-controls="visits" aria-selected="false">Список посещений</button>
                {% else %}
                <button class="nav-link active" style="width: auto; min-width: 88px; padding: 0.25rem;" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Карточка кафе</button>
                <button class="nav-link" style="width: auto; min-width: 88px; padding: 0.25rem;" id="visits-tab" data-bs-toggle="tab" data-bs-target="#visitstable" type="button" role="tab" aria-controls="visits" aria-selected="false">Список посещений</button>
                {% endif %}
                <button class="nav-link" style="width: auto; min-width: 88px; padding: 0.25rem;" id="stories-tab" data-bs-toggle="tab" data-bs-target="#storiestable" type="button" role="tab" aria-controls="stories" aria-selected="false">Истории</button>
            </div>
        </nav>

        <div class="tab-content" id="myTabContent">
            {% if way == 'list' %}
                <div id="home" class="container tab-pane fade" role="tabpanel" aria-labelledby="home-tab">
            {% else %}
                <div id="home" class="container tab-pane show active" role="tabpanel" aria-labelledby="home-tab">
            {% endif %}
                  <div>
                  {% if add %}
                      <p></p><h3 class="modal-title text-center">Новое заведение</h3>
                  {% else %}
                      <p></p><h3 class="modal-title text-center">Кабинет заведения: {{ object }}</h3>
                  {% endif %}
                  </div>
                  <div class="modal-body">

                    <django-formset endpoint="{{ request.path }}" csrf-token="{{ csrf_token }}">
                      {{ form_collection }}
                      <p class="mt-3">
                        {% if perms.core.add_cafemodel %}
                           <button type="button" df-click="submit -> proceed" class="btn btn-primary">Сохранить</button>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <button type="button" df-click="reset" class="ms-2 btn btn-warning">Начальные значения</button>
                        {% endif %}
                      </p>
                    </django-formset>
                  </div>
            </div>

            {% if way == 'list' %}
                <div id="visitstable" class="container h-auto tab-pane active show" role="tabpanel" aria-labelledby="visits-tab">
            {% else %}
                <div id="visitstable" class="container h-auto tab-pane fade" role="tabpanel" aria-labelledby="visits-tab">
            {% endif %}
                <p hx-get="/visits/{{ cafemodel.id }}" tx-target="#cafetable" hx-val="{{ cafemodel.id }}" hx-swap="outerHTML" hx-trigger="load"></p>
            </div>

            <div id="storiestable" class="container h-auto tab-pane fade" role="tabpanel" aria-labelledby="stories-tab">
                <p hx-get="/storytales/{{ cafemodel.id }}" tx-target="#cafetable" hx-val="{{ cafemodel.id }}" hx-swap="outerHTML" hx-trigger="load"></p>
            </div>
        </div>
    </div>
    <script>
        new Carousel(document.getElementById('cardSlider'), {
          Navigation: {
            prevTpl:
              '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11 5l-7 7 7 7"/><path d="M4 12h16"/></svg>',
            nextTpl:
              '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M4 12h16"/><path d="M13 5l7 7-7 7"/></svg>',
          },

          infinite: true,
          center: false,
          slidesPerPage: 'auto',
          transition: false,
        });

        const isStaff = {{ request.user.is_staff|yesno:"true,false" }};         
        document.addEventListener('DOMContentLoaded', function () {
          if (!isStaff) {
              const elements = document.querySelectorAll('[title="Add"].add-collection');
              elements.forEach(el => el.remove());
          }
        });        
    </script>
        
{% endblock %}

core/templates/cafeslist.html
{% extends "minimal.html" %}
{% load cms_tags sekizai_tags menu_tags static %}
{% load render_table from django_tables2 %}
{% load django_bootstrap5 %}

{%  block content %}
    <title>Список кафе</title>

    <br>
    {% if perms.core.add_cafemodel %}
    <div class="container h-auto tab-pane fade active show mt-3">
        <div class="d-grid gap-2 col-10 mx-auto">
            <a class="btn btn-outline-primary" href="/cafe/add_cafe/">
                Добавить кафе
            </a>
        </div>
    </div>
    {% endif %}
    <br>
    <div class="d-grid gap-2 col-10 mx-auto">
        <h3 class="text-center">
            Список кафе и ресторанов:
        </h3>
        <br>
    </div>
    <div class="container h-auto filer-box">
        {# Search form #}

        {% if filter %}
             <form hx-get="{% url 'core:cafes' %}" hx-target="div.table-container">
                  {% bootstrap_form filter.form layout='horizontal' size='sm' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-7' %}
                  {% bootstrap_button 'Искать' size="sm" %}
                  {{ filter.form.media }}
             </form>
        {% endif %}
    </div>

    <div class="container h-auto">
        {% render_table table %}
    </div>
    
{% endblock %}


core/templates/disheslist_htmx.html
{% load django_bootstrap5 %}
{% load render_table from django_tables2 %}

    <br>
        <div class="d-grid gap-2 col-10 mx-auto">
            <a class="btn btn-outline-primary" href="/adddish/{{ visit_id }}">
                Добавить новое блюдо
            </a>
        </div>
    <br>

    <div class="container h-auto filer-box">
        {# Search form #}

        {% if filter %}
             <form hx-get="{% url 'core:dishlist' vpk=visit_id %}" hx-target="#visitstable">
                  {% bootstrap_form filter.form layout='horizontal' size='sm' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-7' %}
                  {% bootstrap_button 'Искать' size="sm" %}
                  {{ filter.form.media }}
             </form>
        {% endif %}
    </div>



{% render_table table %}

core/templates/edit_dish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

core/templates/edit_visit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

core/templates/visits.html
<div id="visitslist">

{#    <button onclick="document.location='add_new_visit'">+</button>#}
<div class="col-10 mx-auto">
    <table class="table table-striped table-hover">

        {% for item in visits %}

            <tr>
{#                <td><a hx-get="{% url 'core:edit_visit' cafe.id item.id %}"#}
                <td><a href="{% url 'core:edit_visit' cafe.id item.id %}"
                >{{ item.data }}  {{ item.description }}</a> {{ item.average_dish_rating }} </td>
            </tr>
        {#    {% url 'core:cab_cafe' item.id %}#}

        {#    <p>"Номер": {{ <item></item>id }}</p>#}

            {#    <a href="{% url 'cab_cafe' %}">кафе</a>#}
        {#    <a {% url 'cab_cafe' item.id %} >ссылка</a>#}
        {#    {% url 'core:cafes' cafe.id %}#}


        {% endfor %}

    </table>
</div>
{#    <form  method="POST">#}
{##}
{#        {% csrf_token %}#}
{#        {{ visitform.as_p }}#}
{##}
{#        <button type="submit" class="btn btn-success" >Сохранить</button>#}
{#        <button id="cancelkey" onclick="javascript:history.go(-1);">Отмена</button>#}
{##}
{#    </form>#}

</div>

core/templates/visits_list_htmx.html
{% load django_bootstrap5 %}
{% load render_table from django_tables2 %}



    <div class="container h-auto filer-box">
        {# Search form #}

        {% if filter %}
             <form hx-get="{% url 'core:visits' pk=cafe_id %}" hx-target="#visitstable">
                  {% bootstrap_form filter.form layout='horizontal' size='sm' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-7' %}
                  {% bootstrap_button 'Искать' size="sm" %}
                  {{ filter.form.media }}
             </form>
        {% endif %}
    </div>


    <div class="container h-auto">
        {% render_table table %}
    </div>