core/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.urls import re_path as url
# from crudbuilder import urls

# from core import views
from .views import (CafeFormsetView, VisitView, TestView, add_dish_library, TableView, dishinfo,
                    add_dish_lib, CafesListView, Cafe_cab, VisitsView, VisitCab,
                    DishesListView, add_new_dish, add_new_dish_collection, TypeDictListView,
                    DictView, TypeEditTableView, TypeDictUpdateListView, ClassDictListView, ClassDictUpdateListView,
                    ClassEditTableView, BestDishesListView, MyVisitsListView,
                    VisitsList, DishPhotosList, StartView, Privacy, StorytalesView
                    )
# from iommi import Form
# from core.models import DishModel
# from iommi.views import crud_views
# from core.models import CulinaryClassModel

app_name = 'core'
urlpatterns = [

    # path('',
    #      RedirectView.as_view(url='/dishes/', permanent=True), name='pages-root'),

    path('', StartView.as_view(), name='start'),
    path('cafes/', CafesListView.as_view(), name='cafes'),

    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^crud/', include(urls)),

    path('dictionaries/', DictView.as_view(), name='dicts'),
    path('dictionaries/types/', TypeDictListView.as_view(), name='types'),
    path('dictionaries/types/<int:tpk>/', TypeDictUpdateListView.as_view(), name='updatetypes'),
    path('edittype/<int:pk>/', TypeEditTableView.as_view(), name='edittype'),

    path('dictionaries/classes/', ClassDictListView.as_view(), name='classes'),
    path('dictionaries/classes/<int:cpk>/', ClassDictUpdateListView.as_view(), name='updateclasses'),
    path('editclass/<int:pk>/', ClassEditTableView.as_view(), name='editclass'),
    # path('iommi/', crud_views(model=CulinaryClassModel)),
    # path('iommi/', iommitest, name='iommi'),

    path('cafe/<int:pk>/', Cafe_cab.as_view(extra_context={'edit': True}), name='cafe_cab'),
    # path('cafe/<int:pk>/?way=list', Cafe_cab.as_view(), name='cafe_cab_list'),

    path('cafe/add_cafe/', Cafe_cab.as_view(extra_context={'add': True}), name='cafe_add'),

    # path('visits/', VisitsView.as_view(), name='visit'),
    path('visits/<int:pk>/', VisitsView.as_view(), name='visits'),

    path('cafe/<int:cpk>/<int:pk>/', VisitCab.as_view(), name='visit'),

    # path('visits/', VisitsView.as_view(), name='allvisits'),

    path('visitcab/<int:cpk>/', VisitCab.as_view(extra_context={'add': True}), name='visitcab'),

    path('disheslist/<int:vpk>/', DishesListView.as_view(), name='dishlist'),

    path('adddish/<int:vpk>/', add_new_dish_collection.as_view(), name='add_new_dish'),

    # path('cafe/<int:cpk>/<int:vpk>/<int:pk>/', add_new_dish.as_view(), name='dishes'),

    path('cafe/<int:cpk>/<int:vpk>/<int:pk>/', add_new_dish_collection.as_view(extra_context={'edit': True}), name='dishes'),

    path('dishinfo/', dishinfo, name='dishinfo'),

    path('dishes/', BestDishesListView.as_view(), name='bestdishes'),

    path('myvisits/', MyVisitsListView.as_view(), name='myvisits'),

    path('visitlist/<int:pk>/', VisitsList.as_view(), name='visitlist'),

    path('dishesphotos/<int:pk>/', DishPhotosList.as_view(), name='visitlist'),

    path('privacy/', Privacy.as_view(), name='visitlist'),

    path('storytales/<int:pk>/', StorytalesView.as_view(), name='storytales'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

foodster/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path as url
# from core.views import DishAutocomplete, TypeOfKitchenAutocomplete
# from core.views import display_cafes, delete_cafe, add_cafe
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog
# from crudbuilder import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    # path(r'^', include('djangocms_forms.urls')),
    # path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('', include('core.urls')),
    # path('rating/', include('rating.urls')),
    # url(r'^photologue/', include('photologue.urls',namespace='photologue')),
    # path('gallery/', include('gallery.urls')),
    path('system/', include('system.urls')),
    # url(r'^dish-autocomplete/$', DishAutocomplete.as_view(create_field='title'), name='dish-autocomplete'),
    # url(r'^typeofkitchen-autocomplete/$', TypeOfKitchenAutocomplete.as_view(create_field='title'), name='typeofkitchen-autocomplete'),
    path(
        'jsi18n/',
        cache_page(3600)(JavaScriptCatalog.as_view(packages=['formset'])),
        name='javascript-catalog'
    ),
    # url(r'^crud/', include(urls)),

]


if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
# if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns


urlpatterns.append(path('', include('cms.urls')))

# the new django admin sidebar is bad UX in django CMS custom admin views.
# admin.site.enable_nav_sidebar = False


urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path as url
# from core.views import DishAutocomplete, TypeOfKitchenAutocomplete
# from core.views import display_cafes, delete_cafe, add_cafe
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog
# from crudbuilder import urls


urlpatterns = [
    path('admin/', admin.site.urls),

    # path(r'^', include('djangocms_forms.urls')),
    # path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    # path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('', include('core.urls')),
    # path('rating/', include('rating.urls')),
    # url(r'^photologue/', include('photologue.urls',namespace='photologue')),
    # path('gallery/', include('gallery.urls')),
    path('system/', include('system.urls')),
    # url(r'^dish-autocomplete/$', DishAutocomplete.as_view(create_field='title'), name='dish-autocomplete'),
    # url(r'^typeofkitchen-autocomplete/$', TypeOfKitchenAutocomplete.as_view(create_field='title'), name='typeofkitchen-autocomplete'),

    path(
        'jsi18n/',
        cache_page(3600)(JavaScriptCatalog.as_view(packages=['formset'])),
        name='javascript-catalog'
    ),
    # url(r'^crud/', include(urls)),

]


if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
# if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns


urlpatterns.append(path('', include('cms.urls')))


# the new django admin sidebar is bad UX in django CMS custom admin views.
# admin.site.enable_nav_sidebar = False

templates/base.html
<!DOCTYPE html>{% load cms_tags menu_tags sekizai_tags static i18n %}{% spaceless %}
<html lang="{{ LANGUAGE_CODE }}" style="height: 100%;" xmlns="http://www.w3.org/1999/html">
        <head>
            <meta charset="utf-8"/>
            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
            {% if request.get_host == "critifood.ru" or request.get_host == "www.critifood.ru" %}
                <meta name="yandex-verification" content="2c76750968f1bb97" />
            {% endif %}
            {% block meta %}
<!--                <meta name="description" content="{% page_attribute meta_description %}"/>-->
                <meta property="og:type" content="website"/>
                <meta property="og:title" content="{% page_attribute "page_title" %}"/>
                <meta property="og:description" content="{% page_attribute meta_description %}"/>
            {% endblock meta %}
            {% block canonical_url %}
                <link rel="canonical" href="{{ request.build_absolute_uri }}"/>
                <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
            {% endblock canonical_url %}
            {% block fb_meta %}{% endblock fb_meta %}
            <title>CritiFood — обзоры ресторанов и блюд</title>
            <meta name="description" content="CritiFood — честные обзоры ресторанов, вкусных блюд. Читайте отзывы, сравнивайте меню и выбирайте лучшее для себя.">
            {% block base_css %}{% endblock %}
{% endspaceless %}{% render_block 'css' %}{% spaceless %}
    {% block page_head %}{% endblock %}
        <style>
            html, body {
                padding-top: 22px;
                height: 100%;
                margin: 0;
            }
            body {
                display: flex;
                flex-direction: column;
            }
            main {
                flex: 1 0 auto;
            }
            footer {
                flex-shrink: 0;
            }
        </style>

        <!-- Yandex.Metrika counter -->
        <script type="text/javascript">
            (function(m,e,t,r,i,k,a){
                m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
                m[i].l=1*new Date();
                for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
                k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
            })(window, document,'script','https://mc.yandex.ru/metrika/tag.js?id=107042384', 'ym');

            ym(107042384, 'init', {ssr:true, webvisor:true, trackHash:true, clickmap:true, referrer: document.referrer, url: location.href, accurateTrackBounce:true, trackLinks:true});
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/107042384" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->

    </head>

      <style>
        :root {
          --bg-rgb-1: 253,251,250;
          --bg-rgb-2: 253,251,250;
          --bg-rgb-3: 253,251,250;
          --bg-rgb-4: 253,251,250;
          --bg-rgb-5: 253,251,250;
          --bg-rgb-6: 253,251,250;
        }

        [data-bs-theme="dark"] {
          --bg-rgb-1: 5,5,5;
          --bg-rgb-2: 5,5,5;
          --bg-rgb-3: 5,5,5;
          --bg-rgb-4: 5,5,5;
          --bg-rgb-5: 5,5,5;
          --bg-rgb-6: 5,5,5;
        }

        body {
          margin: 0;
          min-height: 100vh;
          animation: theme 21s linear infinite;
          font-family: "PT Sans", sans-serif;
        }

        body::after,
        body::before {
          content: '';
          display: block;
          position: fixed;
          z-index: -1;
          top: 0;
          width: 100vw;
          height: 100vh;
          width: 100vmax;
          height: 100vmax;
          background: rgba(var(--bs-emphasis-color-rgb), 0.03);
          animation: background 90s linear infinite;
        }

        body::after {
          left: 15vw;
        }

        body::before {
          right: 15vw;
          animation-delay: -30s;
          animation-direction: reverse;
        }

        @keyframes theme {
          0%   { background-color: rgba(var(--bg-rgb-1), 0.95); }
          16%  { background-color: rgba(var(--bg-rgb-2), 0.95); }
          33%  { background-color: rgba(var(--bg-rgb-3), 0.95); }
          50%  { background-color: rgba(var(--bg-rgb-4), 0.95); }
          66%  { background-color: rgba(var(--bg-rgb-5), 0.95); }
          83%  { background-color: rgba(var(--bg-rgb-6), 0.95); }
          100% { background-color: rgba(var(--bg-rgb-1), 0.95); }
        }

        @keyframes background {
          0% {
            transform: rotate(0deg);
          }
          100% {
            transform: rotate(360deg);
          }
        }

        /* === SVG-иконка по центру === */
        .background-icon {
          position: fixed;
          top: 50%;
          left: 48%;
          transform: translate(-50%, -50%);
          width: 100vw;
          /*max-width: 1200px;*/
          height: auto;
          opacity: 0.03;
          pointer-events: none;
          z-index: -1;
          animation: sway 8s ease-in-out infinite;
        }

        @keyframes sway {
          0% {
            transform: translate(-50%, -50%) rotate(0deg) scale(1);
          }
          25% {
            transform: translate(-50%, -50%) rotate(2deg) scale(1.02);
          }
          75% {
            transform: translate(-50%, -50%) rotate(-2deg) scale(0.98);
          }
          100% {
            transform: translate(-50%, -50%) rotate(0deg) scale(1);
          }
        }

        [data-bs-theme="dark"] .background-icon {
          opacity: 0.05;
        }

        @media (max-width: 768px) {
          .background-icon {
               top: 36%;
               width: 100vw;
            max-width: 800px;
          }
        }

        @media (min-width: 769px) and (max-width: 1200px) {
          .background-icon {
            top: 34%;
            width: 100vw;
            max-width: 1000px;
          }
        }

        @media (min-width: 1201px) and (max-width: 1400px) {
          .background-icon {
            top: 43%;
            width: 100vw;
            max-width: 1100px;
          }
        }


      </style>


    <body {% block body_attrs %}{% endblock %}>
    <img src="{% static 'restaurant-spoon-svgrepo-com.svg' %}" class="background-icon">
{% endspaceless %}{% cms_toolbar %}{% spaceless %}
    {% block navbar %}{% endblock %}
    {% include 'navbar.html' %}
    <main>
    {% block content %}
        {% placeholder "Content" %}
    {% endblock content %}
    </main>
    {% block footer %}{% endblock %}
    {% include 'footer.html' %}
    {% block modal %}
    {% endblock modal %}
    {% block base_js %}{% endblock %}
{% endspaceless %}{% render_block 'js' %}{% spaceless %}
    {% block end_js %}{% endblock %}
    {% block bottom_css %}{% endblock %}


    <div id="cookie-banner" class="cookie-banner hidden">
      <p>Мы используем файлы cookie, чтобы улучшить работу сайта и персонализировать контент. Продолжая использовать сайт, вы соглашаетесь с использованием cookie.</p>
      <div class="cookie-buttons">
        <button id="accept-cookies">Принимаю</button>
        <a href="/privacy/" target="_blank">Подробнее</a>
      </div>
    </div>
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        const banner = document.getElementById('cookie-banner');
        const acceptBtn = document.getElementById('accept-cookies');

        // Проверяем, было ли уже согласие
        if (!localStorage.getItem('cookiesAccepted')) {
          banner.classList.remove('hidden');
        }

        acceptBtn?.addEventListener('click', function () {
          localStorage.setItem('cookiesAccepted', 'true');
          banner.classList.add('hidden');

          // Здесь можно запустить аналитику, например:
          // initAnalytics();
        });

        // Пример отложенной инициализации аналитики
        // function initAnalytics() {
        //   // Загрузка Яндекс.Метрики, GA и т.п.
        // }
      });
    </script>
    </body>
    </html>{% endspaceless %}

templates/footer.html
{% load static %}
<footer class="footer mt-auto">
    <div class="">
        <div class="container mt-5">
            <div class="pt-5 pb-3 text-center">
                Copyright (c) Amikphoto 2026. Вcе права защищены. <a href="/privacy/" target="_blank">Политика обработки персональных данных.</a>
            </div>
        </div>
    </div>
</footer>

templates/minimal.html
{% extends "base.html" %}
{% load static cms_tags sekizai_tags menu_tags %}

{% block body_attrs %}
    data-bs-theme = "light"
{% endblock %}


{% block base_css %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <script src="{% url 'javascript-catalog' %}"></script>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous" media="screen">
    <link href="{% static 'css/bootstrap-utilities.css' %}" rel="stylesheet" crossorigin="anonymous" media="screen">
    <link href="{% static 'formset/css/bootstrap5-extra.css' %}" rel="stylesheet" crossorigin="anonymous" media="screen">
    <link href="{% static 'formset/css/collections.css' %}" rel="stylesheet" crossorigin="anonymous" media="screen">
    <script type="module" src="{% static 'formset/js/django-formset.js' %}"></script>
    <link href="{% static 'css/mycss.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/star.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/fancybox.css' %}" rel="stylesheet" crossorigin="anonymous"/>
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet" crossorigin="anonymous"/>
    <script src="/static/js/fancybox.umd.js"></script>
    <script src="/static/js/carousel.umd.js"></script>

    <link href="{% static 'css/swiper-bundle.min.css' %}" rel="stylesheet" crossorigin="anonymous"/>
    <script src="/static/js/swiper-bundle.min.js"></script>

    <link href="{% static 'css/mycss.css' %}" rel="stylesheet" crossorigin="anonymous">
{#    <link rel="stylesheet" href="{% static 'location_field/css/location_field.css' %}">#}

    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css' crossorigin="anonymous">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" crossorigin="anonymous"></script>

{#    <script src="https://api-maps.yandex.ru/v3/?apikey=34ef8275-9774-4800-9455-5446cb279bc0&lang=ru_RU"></script>#}
    <script src="https://api-maps.yandex.ru/2.1/?apikey=395b3750-9b9d-4e2d-9ff4-e87ccd5b6794&lang=ru_RU" type="text/javascript"></script>
{% endblock %}

{% block base_js %}
        <script src="/static/js/htmx.min.js"></script>
        <script>
              document.body.addEventListener('htmx:configRequest', (event) => {
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
              })
        </script>

    <!--bootstrap working-->
    <script src="/static/js/bootstrap.bundle.js"></script>
    <script src="/static/js/list.js"></script>
    <script src="/static/js/sort.js"></script>


<!--    <script>-->
<!--       Fancybox.bind('[data-fancybox]', {-->
<!--        caption: (fancybox, slide) => {-->
<!--          const caption = slide.caption || "";-->

<!--          return `<br /> ${caption}`;-->
<!--        },-->
<!--      });-->
<!--	 </script>-->
    <script>
        Fancybox.bind('[data-fancybox="gallery"]', {
          compact: false,
          idle: false,

          animated: false,
          showClass: false,
          hideClass: false,

          dragToClose: false,

          Images: {
            // Disable animation from/to thumbnail on start/close
            zoom: false,
          },

          Toolbar: {
            display: {
              left: [],
              middle: [],
              right: ['close', 'rotateCCW', 'rotateCW'],
            },
          },

          Thumbs: {
            type: 'classic',
            Carousel: {
              center: true,
            },
          },

          caption: (fancybox, slide) => {
            const caption = slide.caption || "";

            return `<br /> ${caption}`;
          },

        });
    </script>

{% endblock %}
{% block content %}
    {% placeholder "Content" %}
{% endblock content %}
{% block modal %}
{% endblock modal %}


templates/navbar.html
{% load static menu_tags %}
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a href="/" class="navbar-brand">
                <img src="{% static 'favicon.ico' %}" alt="Logo" class="brand-icon">
                CritiFood
            </a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="{% url 'core:bestdishes' %}" class="nav-item nav-link">Блюда</a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'core:cafes' %}" class="nav-item nav-link">Кафе</a>
                        <a href="{% url 'core:myvisits' %}" class="nav-item nav-link">Мои посещения</a>
                    {% endif %}
                </div>
                <div class="navbar-nav ms-auto">
                    <div class="nav-item">
                    {% show_menu 0 0 0 0 'menu/main_menu.html' %}
                    </div>
                    <div href="{% url 'core:dicts' %}" class="navbar-nav">
                        <i id="toggleThemeButton" class="bi bi-moon"></i>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="dropdown text-end dropstart">
                          <a href="#" class="nav-item nav-link" data-bs-toggle="dropdown" aria-expanded="false">
                              {{ request.user }}
                          </a>
                          <ul class="dropdown-menu text-small dropdown-menu-end dropdown-menu-lg-start" style="">
                            <li><a class="dropdown-item" href="{% url 'profile_detail' request.user.profile.slug %}">Мой профиль</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <Li>
                                <form action="{% url 'logout' %}" method="post">
                                  {% csrf_token %}
                                  <button  class="btn col-10 mx-auto d-grid gap-2" type="submit">Выйти</button>
                                </form>
                            </Li>
                          </ul>
                        </div>
                    {% else %}
                        <ul class="navbar-nav">
                          <li>
                            {% if site_settings.show_register_button %}
                              <a href="{% url 'register' %}" class="nav-item nav-link">Регистрация</a>
                            {% endif %}
                          </li>
                          <li><a href="{% url 'login' %}" class="nav-item nav-link">Вход</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<script>
    // Получаем элемент body
    const body = document.body;

    // Получаем текущую тему из localStorage
    const savedTheme = localStorage.getItem('theme') || 'light';
    body.setAttribute('data-bs-theme', savedTheme);
    const toggleThemeButtonClass = document.getElementById('toggleThemeButton')
    if (savedTheme == 'light') {
        toggleThemeButtonClass.setAttribute('class','bi bi-moon text-primary nav-link')
    } else {
        toggleThemeButtonClass.setAttribute('class','bi bi-sun text-primary nav-link')
    }

    // Добавляем обработчик клика на кнопку
    document.getElementById('toggleThemeButton').addEventListener('click', () => {
      // Определяем новую тему
      const currentTheme = body.getAttribute('data-bs-theme');
      const toggleThemeButtonClass = document.getElementById('toggleThemeButton')
      const newTheme = currentTheme === 'light' ? 'dark' : 'light';
        if (newTheme == 'light') {
            toggleThemeButtonClass.setAttribute('class','bi bi-moon text-primary nav-link')
        } else {
            toggleThemeButtonClass.setAttribute('class','bi bi-sun text-primary nav-link')
        }

      // Устанавливаем новую тему
      body.setAttribute('data-bs-theme', newTheme);

      // Сохраняем тему в localStorage
      localStorage.setItem('theme', newTheme);

    });

</script>